import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Task data",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`antialiased font-[Geist]`}
      >
        {children}
      </body>
    </html>
  );
}
